version: "3"

services:
    web:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./app:/app
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        image: php:fpm
        volumes:
            - ./app:/app

    node:
        image: node
        tty: true
        user: node
        volumes:
            - .:/usr/src/service
        working_dir: /usr/src/service
        command: bash -c "npm install && npm run dev"